### ISSUE TITLE
Problem with synchronisation

### ISSUE THREAD

**Issue by karibertils** [koue/dhcpd#1]
Hello
I am testing the dhcpd synchronisation. I tried first with multicast but could not get it working or see any traffic on port 8067, so i am using unicast which works. I am running on FreeBSD, not sure if i should open the issue here or for the OpenBSD version.

### Dhcp server 1
Interface vlan4040 has IP 172.31.255.0/31
Running /usr/local/sbin/dhcpd -y vlan4040 -Y 172.31.255.1

### Dhcp server 2
Interface vlan4040 has IP 172.31.255.1/31
Running /usr/local/sbin/dhcpd -y vlan4040 -Y 172.31.255.0

### Local switch
Is configured to use both servers as dhcp relay and all dhcp requests go to both.

### Issue
Both servers have tons of duplicate leases in dhcpd.leases. The leases file that used to be around 10-20kb is growing repeatedly above 100kb and then truncating and repeating the process continously. At the same time some entries are only showing up on one server and missing on the other.

There are thousands of entries similar to this that are duplicated:
```
lease 192.168.10.200 {
        starts 0 2020/10/04 20:58:45 UTC;
        ends 0 2020/10/04 21:08:45 UTC;
        hardware ethernet 26:e7:15:a3:de:35;
        client-hostname "DESKTOP-E5C4IE3";
}
lease 192.168.10.200 {
        starts 0 2020/10/04 20:58:45 UTC;
        ends 0 2020/10/04 21:08:45 UTC;
        hardware ethernet 26:e7:15:a3:de:35;
        client-hostname "DESKTOP-E5C4IE3";
}
lease 192.168.10.200 {
        starts 0 2020/10/04 20:58:45 UTC;
        ends 0 2020/10/04 21:08:45 UTC;
        hardware ethernet 26:e7:15:a3:de:35;
        client-hostname "DESKTOP-E5C4IE3";
}
lease 192.168.10.200 {
        starts 0 2020/10/04 20:58:45 UTC;
        ends 0 2020/10/04 21:08:45 UTC;
        hardware ethernet 26:e7:15:a3:de:35;
        client-hostname "DESKTOP-E5C4IE3";
}
lease 192.168.10.200 {
        starts 0 2020/10/04 21:58:45 UTC;
        ends 2 2020/11/03 21:58:45 UTC;
        hardware ethernet 26:e7:15:a3:de:35;
        client-hostname "DESKTOP-E5C4IE3";
}
```

### Both dhcp servers
Md5 sum is the same for /usr/local/etc/dhcpd.conf and /var/db/dhcpd.key on both servers. Tried also without dhcpd.key with same behaviour. Running same everything on both servers.
```
dhcpd-6.6.20200413
Name           : dhcpd
Version        : 6.6.20200413
Installed on   : Sat Oct  3 03:27:30 2020 GMT
Origin         : net/dhcpd
Architecture   : FreeBSD:12:amd64
Prefix         : /usr/local
Categories     : net
Licenses       : BSD3CLAUSE
Maintainer     : koue@chaosophia.net
WWW            : https://github.com/koue/dhcpd
Comment        : OpenBSD dhcp daemon
Options        :
        NOPF           : off
Annotations    :
        FreeBSD_version: 1201000
        repo_type      : binary
        repository     : FreeBSD
Flat size      : 154KiB
Description    :
This is the FreeBSD port of the OpenBSD dhcpd.

The Dynamic Host Configuration Protocol (DHCP) is a standardized
network protocol used on Internet Protocol (IP) networks for dynamically
distributing network configuration parameters, such as IP addresses for
interfaces and services.

WWW: https://github.com/koue/dhcpd
```

**Comment by koue** [comment]
Thanks for reporting this issue!

I will work on the issue but I'll need some time.

**Comment by koue** [comment]
Hello,

I did testing with two servers running `dhcpd 6.6.20200413` installed as package with pkg and one client. All three nodes are running `FreeBSD 12.1 amd64` and they are using `em0` network interface. There is no smart switch in the network configuration, all nodes are virtual machines.

Every 5 minutes the client is sending single request. After sending reply to the client the server is sending sync message over port 8067 to the other server. Either one of the servers is replying to the client or both of them. Either way `new single entry` appears in both `dhcpd.leases` files. According to https://man.openbsd.org/dhcpd.leases.5: 

> This database is a free-form ASCII file containing a series of lease declarations. Every time a lease is acquired, renewed or released, its new value is recorded at the end of the lease file. So if more than one declaration appears for a given lease, the last one in the file is the current one.

And it works as expected, new single entry every 5 minutes for every request. Also servers are not sending sync messages for old leases. They are sending sync messages only if both servers are online during the lease changes. This could explain why there are differences in the lease files.  About the duplicate entries in the lease file I will monitor the UDP traffic on the server side. My guess is the server is receiving multiple UDP packages for the same request.
